=== jkneal/kradtraining/training/rice/db/impex/client/bootstrap/src/main/resources/data.dtd
<!ELEMENT dataset (
    KRAD_MSG_T|
    KRNS_ADHOC_RTE_ACTN_RECIP_T|
    KRNS_ATT_T|
    KRNS_DOC_HDR_T|
    KRNS_LOOKUP_RSLT_T|
    KRNS_LOOKUP_SEL_T|
    KRNS_MAINT_DOC_ATT_LST_T|
    KRNS_MAINT_DOC_ATT_T|
    KRNS_MAINT_DOC_T|
    KRNS_MAINT_LOCK_T|
    KRNS_NTE_T|
    KRNS_NTE_TYP_T|
    KRNS_PESSIMISTIC_LOCK_T|
    KRNS_SESN_DOC_T|
    KRSB_BAM_PARM_T|
    KRSB_BAM_T|
    KRSB_MSG_PYLD_T|
    KRSB_MSG_QUE_T|
    KRSB_QRTZ_BLOB_TRIGGERS|
    KRSB_QRTZ_CALENDARS|
    KRSB_QRTZ_CRON_TRIGGERS|
    KRSB_QRTZ_FIRED_TRIGGERS|
    KRSB_QRTZ_JOB_DETAILS|
    KRSB_QRTZ_JOB_LISTENERS|
    KRSB_QRTZ_LOCKS|
    KRSB_QRTZ_PAUSED_TRIGGER_GRPS|
    KRSB_QRTZ_SCHEDULER_STATE|
    KRSB_QRTZ_SIMPLE_TRIGGERS|
    KRSB_QRTZ_TRIGGERS|
    KRSB_QRTZ_TRIGGER_LISTENERS)*>
<!ELEMENT KRAD_MSG_T EMPTY>
<!ATTLIST KRAD_MSG_T
    NMSPC_CD CDATA #IMPLIED
    CMPNT_CD CDATA #IMPLIED
    MSG_KEY CDATA #IMPLIED
    LOC CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
    MSG_DESC CDATA #IMPLIED
    TXT CDATA #IMPLIED
>

<!ELEMENT KRNS_ADHOC_RTE_ACTN_RECIP_T EMPTY>
<!ATTLIST KRNS_ADHOC_RTE_ACTN_RECIP_T
    RECIP_TYP_CD CDATA #IMPLIED
    ACTN_RQST_CD CDATA #IMPLIED
    ACTN_RQST_RECIP_ID CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
    DOC_HDR_ID CDATA #IMPLIED
>

<!ELEMENT KRNS_ATT_T EMPTY>
<!ATTLIST KRNS_ATT_T
    NTE_ID CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
    MIME_TYP CDATA #IMPLIED
    FILE_NM CDATA #IMPLIED
    ATT_ID CDATA #IMPLIED
    FILE_SZ CDATA #IMPLIED
    ATT_TYP_CD CDATA #IMPLIED
>

<!ELEMENT KRNS_DOC_HDR_T EMPTY>
<!ATTLIST KRNS_DOC_HDR_T
    DOC_HDR_ID CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
    FDOC_DESC CDATA #IMPLIED
    ORG_DOC_HDR_ID CDATA #IMPLIED
    TMPL_DOC_HDR_ID CDATA #IMPLIED
    EXPLANATION CDATA #IMPLIED
>

<!ELEMENT KRNS_LOOKUP_RSLT_T EMPTY>
<!ATTLIST KRNS_LOOKUP_RSLT_T
    LOOKUP_RSLT_ID CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
    PRNCPL_ID CDATA #REQUIRED
    LOOKUP_DT CDATA #REQUIRED
    SERIALZD_RSLTS CDATA #IMPLIED
>

<!ELEMENT KRNS_LOOKUP_SEL_T EMPTY>
<!ATTLIST KRNS_LOOKUP_SEL_T
    LOOKUP_RSLT_ID CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
    PRNCPL_ID CDATA #REQUIRED
    LOOKUP_DT CDATA #REQUIRED
    SEL_OBJ_IDS CDATA #IMPLIED
>

<!ELEMENT KRNS_MAINT_DOC_ATT_LST_T EMPTY>
<!ATTLIST KRNS_MAINT_DOC_ATT_LST_T
    ATT_ID CDATA #IMPLIED
    DOC_HDR_ID CDATA #REQUIRED
    ATT_CNTNT CDATA #REQUIRED
    FILE_NM CDATA #IMPLIED
    CNTNT_TYP CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
>

<!ELEMENT KRNS_MAINT_DOC_ATT_T EMPTY>
<!ATTLIST KRNS_MAINT_DOC_ATT_T
    DOC_HDR_ID CDATA #IMPLIED
    ATT_CNTNT CDATA #REQUIRED
    FILE_NM CDATA #IMPLIED
    CNTNT_TYP CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
>

<!ELEMENT KRNS_MAINT_DOC_T EMPTY>
<!ATTLIST KRNS_MAINT_DOC_T
    DOC_HDR_ID CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
    DOC_CNTNT CDATA #IMPLIED
>

<!ELEMENT KRNS_MAINT_LOCK_T EMPTY>
<!ATTLIST KRNS_MAINT_LOCK_T
    MAINT_LOCK_REP_TXT CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
    DOC_HDR_ID CDATA #REQUIRED
    MAINT_LOCK_ID CDATA #IMPLIED
>

<!ELEMENT KRNS_NTE_T EMPTY>
<!ATTLIST KRNS_NTE_T
    NTE_ID CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
    RMT_OBJ_ID CDATA #REQUIRED
    AUTH_PRNCPL_ID CDATA #REQUIRED
    POST_TS CDATA #REQUIRED
    NTE_TYP_CD CDATA #REQUIRED
    TXT CDATA #IMPLIED
    PRG_CD CDATA #IMPLIED
    TPC_TXT CDATA #IMPLIED
>

<!ELEMENT KRNS_NTE_TYP_T EMPTY>
<!ATTLIST KRNS_NTE_TYP_T
    NTE_TYP_CD CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
    TYP_DESC_TXT CDATA #IMPLIED
    ACTV_IND CDATA #IMPLIED
>

<!ELEMENT KRNS_PESSIMISTIC_LOCK_T EMPTY>
<!ATTLIST KRNS_PESSIMISTIC_LOCK_T
    PESSIMISTIC_LOCK_ID CDATA #IMPLIED
    OBJ_ID CDATA #REQUIRED
    VER_NBR CDATA #REQUIRED
    LOCK_DESC_TXT CDATA #IMPLIED
    DOC_HDR_ID CDATA #REQUIRED
    GNRT_DT CDATA #REQUIRED
    PRNCPL_ID CDATA #REQUIRED
    SESN_ID CDATA #REQUIRED
>

<!ELEMENT KRNS_SESN_DOC_T EMPTY>
<!ATTLIST KRNS_SESN_DOC_T
    SESN_DOC_ID CDATA #IMPLIED
    DOC_HDR_ID CDATA #IMPLIED
    PRNCPL_ID CDATA #IMPLIED
    IP_ADDR CDATA #IMPLIED
    SERIALZD_DOC_FRM CDATA #IMPLIED
    LAST_UPDT_DT CDATA #IMPLIED
    CONTENT_ENCRYPTED_IND CDATA #IMPLIED
    OBJ_ID CDATA #IMPLIED
    VER_NBR CDATA #IMPLIED
>

<!ELEMENT KRSB_BAM_PARM_T EMPTY>
<!ATTLIST KRSB_BAM_PARM_T
    BAM_PARM_ID CDATA #IMPLIED
    BAM_ID CDATA #REQUIRED
    PARM CDATA #REQUIRED
>

<!ELEMENT KRSB_BAM_T EMPTY>
<!ATTLIST KRSB_BAM_T
    BAM_ID CDATA #IMPLIED
    SVC_NM CDATA #REQUIRED
    SVC_URL CDATA #REQUIRED
    MTHD_NM CDATA #REQUIRED
    THRD_NM CDATA #REQUIRED
    CALL_DT CDATA #REQUIRED
    TGT_TO_STR CDATA #REQUIRED
    SRVR_IND CDATA #REQUIRED
    EXCPN_TO_STR CDATA #IMPLIED
    EXCPN_MSG CDATA #IMPLIED
>

<!ELEMENT KRSB_MSG_PYLD_T EMPTY>
<!ATTLIST KRSB_MSG_PYLD_T
    MSG_QUE_ID CDATA #IMPLIED
    MSG_PYLD CDATA #REQUIRED
>

<!ELEMENT KRSB_MSG_QUE_T EMPTY>
<!ATTLIST KRSB_MSG_QUE_T
    MSG_QUE_ID CDATA #IMPLIED
    DT CDATA #REQUIRED
    EXP_DT CDATA #IMPLIED
    PRIO CDATA #REQUIRED
    STAT_CD CDATA #REQUIRED
    RTRY_CNT CDATA #REQUIRED
    IP_NBR CDATA #REQUIRED
    SVC_NM CDATA #IMPLIED
    APPL_ID CDATA #REQUIRED
    SVC_MTHD_NM CDATA #IMPLIED
    APP_VAL_ONE CDATA #IMPLIED
    APP_VAL_TWO CDATA #IMPLIED
    VER_NBR CDATA #IMPLIED
>

<!ELEMENT KRSB_QRTZ_BLOB_TRIGGERS EMPTY>
<!ATTLIST KRSB_QRTZ_BLOB_TRIGGERS
    TRIGGER_NAME CDATA #IMPLIED
    TRIGGER_GROUP CDATA #IMPLIED
    BLOB_DATA CDATA #IMPLIED
>

<!ELEMENT KRSB_QRTZ_CALENDARS EMPTY>
<!ATTLIST KRSB_QRTZ_CALENDARS
    CALENDAR_NAME CDATA #IMPLIED
    CALENDAR CDATA #REQUIRED
>

<!ELEMENT KRSB_QRTZ_CRON_TRIGGERS EMPTY>
<!ATTLIST KRSB_QRTZ_CRON_TRIGGERS
    TRIGGER_NAME CDATA #IMPLIED
    TRIGGER_GROUP CDATA #IMPLIED
    CRON_EXPRESSION CDATA #REQUIRED
    TIME_ZONE_ID CDATA #IMPLIED
>

<!ELEMENT KRSB_QRTZ_FIRED_TRIGGERS EMPTY>
<!ATTLIST KRSB_QRTZ_FIRED_TRIGGERS
    ENTRY_ID CDATA #IMPLIED
    TRIGGER_NAME CDATA #REQUIRED
    TRIGGER_GROUP CDATA #REQUIRED
    IS_VOLATILE CDATA #REQUIRED
    INSTANCE_NAME CDATA #REQUIRED
    FIRED_TIME CDATA #REQUIRED
    PRIORITY CDATA #REQUIRED
    STATE CDATA #REQUIRED
    JOB_NAME CDATA #IMPLIED
    JOB_GROUP CDATA #IMPLIED
    IS_STATEFUL CDATA #IMPLIED
    REQUESTS_RECOVERY CDATA #IMPLIED
>

<!ELEMENT KRSB_QRTZ_JOB_DETAILS EMPTY>
<!ATTLIST KRSB_QRTZ_JOB_DETAILS
    JOB_NAME CDATA #IMPLIED
    JOB_GROUP CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    JOB_CLASS_NAME CDATA #REQUIRED
    IS_DURABLE CDATA #REQUIRED
    IS_VOLATILE CDATA #REQUIRED
    IS_STATEFUL CDATA #REQUIRED
    REQUESTS_RECOVERY CDATA #REQUIRED
    JOB_DATA CDATA #IMPLIED
>

<!ELEMENT KRSB_QRTZ_JOB_LISTENERS EMPTY>
<!ATTLIST KRSB_QRTZ_JOB_LISTENERS
    JOB_NAME CDATA #IMPLIED
    JOB_GROUP CDATA #IMPLIED
    JOB_LISTENER CDATA #IMPLIED
>

<!ELEMENT KRSB_QRTZ_LOCKS EMPTY>
<!ATTLIST KRSB_QRTZ_LOCKS
    LOCK_NAME CDATA #IMPLIED
>

<!ELEMENT KRSB_QRTZ_PAUSED_TRIGGER_GRPS EMPTY>
<!ATTLIST KRSB_QRTZ_PAUSED_TRIGGER_GRPS
    TRIGGER_GROUP CDATA #IMPLIED
>

<!ELEMENT KRSB_QRTZ_SCHEDULER_STATE EMPTY>
<!ATTLIST KRSB_QRTZ_SCHEDULER_STATE
    INSTANCE_NAME CDATA #IMPLIED
    LAST_CHECKIN_TIME CDATA #REQUIRED
    CHECKIN_INTERVAL CDATA #REQUIRED
>

<!ELEMENT KRSB_QRTZ_SIMPLE_TRIGGERS EMPTY>
<!ATTLIST KRSB_QRTZ_SIMPLE_TRIGGERS
    TRIGGER_NAME CDATA #IMPLIED
    TRIGGER_GROUP CDATA #IMPLIED
    REPEAT_COUNT CDATA #REQUIRED
    REPEAT_INTERVAL CDATA #REQUIRED
    TIMES_TRIGGERED CDATA #REQUIRED
>

<!ELEMENT KRSB_QRTZ_TRIGGERS EMPTY>
<!ATTLIST KRSB_QRTZ_TRIGGERS
    TRIGGER_NAME CDATA #IMPLIED
    TRIGGER_GROUP CDATA #IMPLIED
    JOB_NAME CDATA #REQUIRED
    JOB_GROUP CDATA #REQUIRED
    IS_VOLATILE CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    NEXT_FIRE_TIME CDATA #IMPLIED
    PREV_FIRE_TIME CDATA #IMPLIED
    PRIORITY CDATA #IMPLIED
    TRIGGER_STATE CDATA #REQUIRED
    TRIGGER_TYPE CDATA #REQUIRED
    START_TIME CDATA #REQUIRED
    END_TIME CDATA #IMPLIED
    CALENDAR_NAME CDATA #IMPLIED
    MISFIRE_INSTR CDATA #IMPLIED
    JOB_DATA CDATA #IMPLIED
>

<!ELEMENT KRSB_QRTZ_TRIGGER_LISTENERS EMPTY>
<!ATTLIST KRSB_QRTZ_TRIGGER_LISTENERS
    TRIGGER_NAME CDATA #IMPLIED
    TRIGGER_GROUP CDATA #IMPLIED
    TRIGGER_LISTENER CDATA #IMPLIED
>

=== jkneal/kradtraining/training/rice/db/impex/master/src/main/resources/KRNS_DOC_HDR_T.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "data.dtd">
<!--  Auto-generated by the Maven Impex Plugin -->
<dataset>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2123" FDOC_DESC="rewer"
        OBJ_ID="A1CE1FBC-4CB8-672E-0CA0-8CF1F9E7001B" ORG_DOC_HDR_ID="1" VER_NBR="4"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2381" FDOC_DESC="test"
        OBJ_ID="5376DA5C-E693-65A5-E1B4-B403660B5315" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2382" FDOC_DESC="test"
        OBJ_ID="1586F905-5C0A-5348-72A4-BF9ECDD1967F" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2383" FDOC_DESC="a5"
        OBJ_ID="00375DE1-4F36-8000-DA86-B731D73FFE03" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2384" FDOC_DESC="asdf"
        OBJ_ID="BD50B601-2F27-184A-6349-52F696F1927B" VER_NBR="5"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2387" FDOC_DESC="test trans doc"
        OBJ_ID="5FECE942-58D1-CCA7-36D9-F47AD78EEE89" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2388" FDOC_DESC="test trans doc 2"
        OBJ_ID="30034849-5137-0893-9871-87B1D8015D77" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2389" FDOC_DESC="test trans doc 3"
        OBJ_ID="889E14B3-B2C4-1B46-6B95-FDA71509360B" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2390" FDOC_DESC="test trans doc 4"
        OBJ_ID="D97C2F77-0CAE-0CF4-BBC8-F7D83143A72D" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2391" FDOC_DESC="test trans doc 5"
        OBJ_ID="FA4C747D-D12F-FBE5-4841-5FE813973D3F" VER_NBR="3"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2392" FDOC_DESC="a8"
        OBJ_ID="37681271-55AD-67D3-994D-9438CC088A2C" VER_NBR="5"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2393" FDOC_DESC="asdf"
        OBJ_ID="494D43EF-7987-2726-4F0D-2C3817A28A87" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2394" FDOC_DESC="asdf"
        OBJ_ID="D0E4F8A1-617C-6819-3DBE-5189C9248E43" VER_NBR="5"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2396" FDOC_DESC="asdf"
        OBJ_ID="128456EF-B9B4-D940-FFF8-2DD5E66312D6" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2400" FDOC_DESC="asdf"
        OBJ_ID="FFB6EF95-9B5B-85DB-7044-5F72EAC68615" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2401" FDOC_DESC="dsaf"
        OBJ_ID="CA3E068D-CA02-190F-FE25-0E3DCBA14C96" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2402" FDOC_DESC="sdfa"
        OBJ_ID="35BC7B93-8288-5D36-D32A-1B1096094081" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2403" FDOC_DESC="sadf"
        OBJ_ID="80729320-661F-9133-473B-69E0138D4A9B" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2404" FDOC_DESC="ASDf"
        OBJ_ID="38735150-77D3-BA30-3B01-D7F025C15FAA" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2405" FDOC_DESC="sdaf"
        OBJ_ID="D3537A08-6173-4DD8-B925-E3493F587DCD" VER_NBR="4"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2406" FDOC_DESC="a14"
        OBJ_ID="36A06489-8F83-C489-455F-A1D4A9082248" VER_NBR="5"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2407" FDOC_DESC="dsaf"
        OBJ_ID="539F5EAB-CFBB-16D8-E7C0-6326793DCDB3" VER_NBR="4"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2410" FDOC_DESC="sadf"
        OBJ_ID="0A69E828-1BE0-CC72-FB18-A518033184E7" VER_NBR="5"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2480" FDOC_DESC="nate"
        OBJ_ID="A1DACA08-BA46-F2CC-F3E6-2F5C7FA9ACC4" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2481" FDOC_DESC="nate2"
        OBJ_ID="39EE9595-5121-1527-0E6E-B1380A1A13A7" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2482" FDOC_DESC="nate3"
        OBJ_ID="26ECE1C4-077D-2772-312D-B03B14D117FB" VER_NBR="4"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2483" FDOC_DESC="nate after convertions"
        OBJ_ID="6948923D-524D-3990-EAF6-28247E1B1904" VER_NBR="4"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2484" FDOC_DESC="one more"
        OBJ_ID="BAB7E16B-792C-26A6-80DB-5FAACFC45CF1" VER_NBR="4"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2500" FDOC_DESC="testing patch"
        OBJ_ID="6B2F08FD-15C4-72F2-10C2-E887F5C6752E" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2501" FDOC_DESC="testing patch 2"
        OBJ_ID="ECF3E5A5-E5A3-0EB9-38E6-510D71084E9D" VER_NBR="4"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2520" FDOC_DESC="2234"
        OBJ_ID="EE1240AF-EA07-F774-0B1C-7483C853FB3E" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2521" FDOC_DESC="asdfsd"
        OBJ_ID="2028AB52-184F-86E2-0BD3-8CE296CF2F84" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2522" FDOC_DESC="sadf"
        OBJ_ID="F0FDB682-C109-CD1F-EB32-347A7D04270D" VER_NBR="4"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2584" FDOC_DESC="sadsadsadas"
        OBJ_ID="4A9A559F-9D10-9B92-E814-60F82E392853" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2640" EXPLANATION="dsf" FDOC_DESC="test"
        OBJ_ID="1F360AC6-6DCD-BFA2-63E3-B5027F41B391"
        ORG_DOC_HDR_ID="123" VER_NBR="4"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2692" FDOC_DESC="test"
        OBJ_ID="8ED05623-5D21-C6ED-715F-CEF4E3C43D30" ORG_DOC_HDR_ID="1" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2693" FDOC_DESC="test"
        OBJ_ID="59108177-A298-55C3-2595-DAFD985F67F2" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2694" FDOC_DESC="esdf"
        OBJ_ID="58EF3839-6297-549E-FCB1-B23144800B0E" VER_NBR="2"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2695" FDOC_DESC="dfads"
        OBJ_ID="575820F1-EE03-E7C8-F32B-9640D0D25B5A" VER_NBR="7"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2700"
        FDOC_DESC="Create a new delegation rule for test"
        OBJ_ID="CCE4C116-CE7C-2D35-759B-E9C28D7CFAAB" VER_NBR="5"/>
    <KRNS_DOC_HDR_T DOC_HDR_ID="2701" FDOC_DESC="test"
        OBJ_ID="564A761C-6CCD-2E0B-6AC7-E528B655CA60" VER_NBR="2"/>
</dataset>
